Process input handler refactor
Pending-Name-21/frontend-library pull request #27
Opened 2024-06-26 18:28 UTC by zrock-dev

# Task-207 Implementation of Input intermediate

https://tree.taiga.io/project/joseluis-teran-coffeetime/task/207

## Description
Implementation of : https://github.com/Pending-Name-21/arquitecture/pull/20

## Type of Change

Put an `x` in all the boxes that apply:

- [ ] ✨ New Feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug Fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking Change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code Refactor
- [ ] ✅ Build Configuration Change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Pull Request Checklist

Put an `x` in all the boxes that apply:

- [x] My commit messages are detailed.
- [x] My code follows the code style of this project.
- [ ] No existing features have been broken without good reason.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests pass.

2024-06-26 18:51 UTC, codeFactory12 requested changes

2024-06-26 18:51 UTC, codeFactory12 commented on bridge/src/main/java/com/bridge/processinputhandler/AEventManager.java
> +
src/main/java/com/bridge/processinputhandler/AEventManager.java
          @@ -1,7 +1,6 @@
           package·com.bridge.processinputhandler;
           
           import·com.bridge.ipc.IEventBuffer;
          -
           import·java.util.ArrayList;
           import·java.util.List;
           import·java.util.concurrent.ConcurrentLinkedQueue;
Doesnt acomlish with format, review with ./gradlew build

Run './gradlew :bridge:spotlessApply'

2024-06-26 18:54 UTC, codeFactory12 commented on bridge/src/main/java/com/bridge/processinputhandler/AEventManager.java
> +
There are more archieves that needs a format fix such us:
src/test/java/com/bridge/ipc/ReceiverTest.java
src/test/java/com/bridge/processinputhandler/AEventManagerTest.java
src/test/java/com/bridge/processinputhandler/InputVerifierTest.java
src/test/java/com/bridge/GameTest.java
src/test/java/com/bridge/EventGenerator.java
src/main/java/com/bridge/processinputhandler/IPublisher.java
can be fixed using : **./gradlew :bridge:spotlessApply**

2024-06-26 19:32 UTC, codeFactory12 requested changes
There are errors in tests clases that are not uploeaded sich us 
test/java/com/bidge
ipc/SocketServerTest
Expected 0 arguments but found 1 on line 13
processinputhandler/EventTypeTest
Cannot resolve symbol 'EventType' on line 12
GameWithExceptionsTest
Cannot resolve symbol 'Utils'

2024-06-26 19:32 UTC, codeFactory12 commented on bridge/src/test/java/com/bridge/GameTest.java
> +import com.bridge.processinputhandler.MouseEventManager;
There is no MouseEventManager uploaded

2024-06-26 19:32 UTC, codeFactory12 commented on bridge/src/main/java/com/bridge/processinputhandler/KeyboardEventManager.java
>       * @param buffer the concurrent linked queue used to store keyboard events
Cannot resolve symbol 'buffer' on line 32

2024-06-26 22:44 UTC, codeFactory12 approved these changes
Nice joob

2024-06-27 03:22 UTC, fabianromeroclaros approved these changes

2024-06-27 12:17 UTC, merged